import type { Hospital } from "./types";

export const hospitals: Hospital[] = [
  {
    id: 1,
    name: "강남서울내과의원",
    addr: "서울특별시 강남구 테헤란로 125",
    number: "02-555-1200",
    openStatus: true,
    waitingPeople: 7,
    waitingTime: 24,
    rating: 4.8,
  },
  {
    id: 2,
    name: "서초푸른소아청소년과의원",
    addr: "서울특별시 서초구 서초대로 77",
    number: "02-3477-2200",
    openStatus: true,
    waitingPeople: 11,
    waitingTime: 38,
    rating: 4.7,
  },
  {
    id: 3,
    name: "송파바른정형외과의원",
    addr: "서울특별시 송파구 올림픽로 300",
    number: "02-423-8900",
    openStatus: true,
    waitingPeople: 4,
    waitingTime: 16,
    rating: 4.6,
  },
  {
    id: 4,
    name: "마포연세이비인후과의원",
    addr: "서울특별시 마포구 월드컵북로 45",
    number: "02-3144-7100",
    openStatus: true,
    waitingPeople: 14,
    waitingTime: 46,
    rating: 4.9,
  },
  {
    id: 5,
    name: "노원미소치과의원",
    addr: "서울특별시 노원구 동일로 1400",
    number: "02-939-2800",
    openStatus: true,
    waitingPeople: 2,
    waitingTime: 10,
    rating: 4.5,
  },
  {
    id: 6,
    name: "제주연동맑은내과의원",
    addr: "제주특별자치도 제주시 연북로 45",
    number: "064-746-1100",
    openStatus: false,
    waitingPeople: 0,
    waitingTime: 0,
    rating: 4.3,
  },
];
