import type { Hospital } from "./types";

export const hospitals: Hospital[] = [
  {
    id: "gangnam-care",
    name: "강남포근내과",
    specialty: "내과",
    address: "서울 강남구 테헤란로 125",
    phone: "02-555-1200",
    waitingCount: 7,
    estimatedMinutes: 24,
    openStatus: "진료중",
    rating: 4.8,
    accentColor: "from-teal-500 to-sky-600",
  },
  {
    id: "daejeon-kids",
    name: "대전아이소아과",
    specialty: "소아청소년과",
    address: "대전 서구 둔산로 88",
    phone: "042-321-7000",
    waitingCount: 11,
    estimatedMinutes: 38,
    openStatus: "진료중",
    rating: 4.7,
    accentColor: "from-amber-400 to-orange-500",
  },
  {
    id: "busan-bone",
    name: "부산튼튼정형외과",
    specialty: "정형외과",
    address: "부산 해운대구 센텀중앙로 45",
    phone: "051-770-3000",
    waitingCount: 4,
    estimatedMinutes: 16,
    openStatus: "진료중",
    rating: 4.6,
    accentColor: "from-blue-500 to-indigo-600",
  },
  {
    id: "gwangju-ent",
    name: "광주맑은이비인후과",
    specialty: "이비인후과",
    address: "광주 북구 첨단연신로 32",
    phone: "062-919-0101",
    waitingCount: 14,
    estimatedMinutes: 46,
    openStatus: "진료중",
    rating: 4.9,
    accentColor: "from-cyan-500 to-teal-600",
  },
  {
    id: "suwon-dental",
    name: "수원미소치과",
    specialty: "치과",
    address: "경기 수원시 팔달구 권광로 181",
    phone: "031-240-9000",
    waitingCount: 2,
    estimatedMinutes: 10,
    openStatus: "진료중",
    rating: 4.5,
    accentColor: "from-violet-500 to-fuchsia-600",
  },
  {
    id: "daegu-skin",
    name: "대구온빛피부과",
    specialty: "피부과",
    address: "대구 중구 동성로 27",
    phone: "053-421-8080",
    waitingCount: 0,
    estimatedMinutes: 0,
    openStatus: "접수마감",
    rating: 4.4,
    accentColor: "from-rose-400 to-pink-600",
  },
];
